use_frameworks!

target 'Spider_Example' do

    pod 'Spider-Web/All', :path => '../'
    pod 'SnapKit',        '~> 5.0'
    
    target 'Spider_Tests' do
        inherit! :search_paths
    end
    
    post_install do |installer|

        # Fix for M1 Mac compilation
      
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
            end
        end
      
        # Fix for Xcode 14 compilation
      
        installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                        
                    deployment_target = config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"]
                    deployment_target_major = deployment_target.split(".").first.to_i
            
                    if deployment_target_major < 11
                        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
                    end
            
                end
            end
        end
      
    end

end
