use_frameworks!

target 'Spider_Example' do

  # Temporary override for Swift 4 migration
  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift4-beta1'
  
  pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'swift-4'
  pod 'Spider-Web', :path => '../'
  
  target 'Spider_Tests' do
    inherit! :search_paths
  end

end
